# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 316c3859060e239645abf2fa4689a848409b16d2a2770b35bad67a1c5f7b42efa8bdf2a66e688ef75e2556ad9ac618fa2b8ca76b0ea5eaf4b72507a949e996d7

test:
  secret_key_base: a01587353cc55f967822b06bd7d2cba5a47f0e1a2faae20700f859822083d46e126b55306108a9cd4bd01e51a4b2ab3ad82fb4c18b36083ba34e313d53c4cbdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
